### ISSUE TITLE
[Bug]: get_stock_snapshot causes an exception for certain tickers

### ISSUE THREAD

**Issue by kmecpp** [alpacahq/alpaca-py#157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
Traceback (most recent call last):
    snapshots = historical_data_client.get_stock_snapshot(StockSnapshotRequest(symbol_or_symbols=['AAPL', 'KUBTY']))
  File "venv/lib/python3.10/site-packages/alpaca/data/historical/stock.py", line 237, in get_stock_snapshot
    return parse_obj_as_symbol_dict(Snapshot, raw_snapshots)
  File "venv/lib/python3.10/site-packages/alpaca/data/historical/utils.py", line 26, in parse_obj_as_symbol_dict
    return {k: model(symbol=k, raw_data=v) for k, v in raw_data.items()}
  File "venv/lib/python3.10/site-packages/alpaca/data/historical/utils.py", line 26, in <dictcomp>
    return {k: model(symbol=k, raw_data=v) for k, v in raw_data.items()}
  File "venv/lib/python3.10/site-packages/alpaca/data/models/snapshots.py", line 38, in __init__
    for key, val in raw_data.items()
AttributeError: 'NoneType' object has no attribute 'items'
```

KUBTY is a perfectly valid asset but for some reason the API is returning null for it's snapshot:
```
id=UUID('eeb8c04d-fd33-4af6-b1cd-f0475db7b43b') asset_class=<AssetClass.US_EQUITY: 'us_equity'> exchange=<AssetExchange.OTC: 'OTC'> symbol='KUBTY' name='Kubota Corporation' status=<AssetStatus.ACTIVE: 'active'> tradable=True marginable=False shortable=True easy_to_borrow=True fractionable=True
```

The same behavior occurs if the request contains an non-existent asset ticker

### Expected Behavior

Data should still be able to be retrieved for other tickers even if the request contains some tickers for which there is no snapshot data.

### SDK Version I encountered this issue in

0.5.4

### Steps To Reproduce

```markdown
historical_data_client.get_stock_snapshot(StockSnapshotRequest(symbol_or_symbols=['AAPL', 'KUBTY']))
```
```


### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

### Anything else?

_No response_

**Comment by tyree731** [comment]
Just wanted note that I saw a similar, though not exactly the same, exception in `get_stock_bars`:

```
... stack trace here and above is our code
[2022-11-01, 19:41:40 UTC] {pod_manager.py:226} INFO -     alpaca_results = alpaca_client.get_stock_bars(request)
[2022-11-01, 19:41:40 UTC] {pod_manager.py:226} INFO -   File "/opt/venv/lib/python3.8/site-packages/alpaca/data/historical/stock.py", line 99, in get_stock_bars
[2022-11-01, 19:41:40 UTC] {pod_manager.py:226} INFO -     return BarSet(raw_bars)
[2022-11-01, 19:41:40 UTC] {pod_manager.py:226} INFO -   File "/opt/venv/lib/python3.8/site-packages/alpaca/data/models/bars.py", line 73, in __init__
[2022-11-01, 19:41:40 UTC] {pod_manager.py:226} INFO -     parsed_bars[symbol] = [Bar(symbol, bar) for bar in bars]
[2022-11-01, 19:41:40 UTC] {pod_manager.py:226} INFO -   File "/opt/venv/lib/python3.8/site-packages/alpaca/data/models/bars.py", line 73, in <listcomp>
[2022-11-01, 19:41:40 UTC] {pod_manager.py:226} INFO -     parsed_bars[symbol] = [Bar(symbol, bar) for bar in bars]
[2022-11-01, 19:41:40 UTC] {pod_manager.py:226} INFO -   File "/opt/venv/lib/python3.8/site-packages/alpaca/data/models/bars.py", line 43, in __init__
[2022-11-01, 19:41:40 UTC] {pod_manager.py:226} INFO -     BAR_MAPPING[key]: val for key, val in raw_data.items() if key in BAR_MAPPING
[2022-11-01, 19:41:40 UTC] {pod_manager.py:226} INFO - AttributeError: 'NoneType' object has no attribute 'items'```

It seems to happen to us for any securities which have been delisted, and thus return a `null` value for their data. What is the guidance for capturing these events, catching `AttributeError`?

**Comment by tyree731** [comment]
Any update here? It's been almost a month since the last comment.

**Comment by tyree731** [comment]
Is this library even maintained? What is happening here?

**Comment by RiverRo** [comment]
Just had this happen to $AZTR. In this case, it's a recent IPO and this ticker has no value for 'prevDailyBar' in the raw data. 
 When the bars model receives this raw data to to cast it into Bar, it doesn't have a check for None before it calls `raw_data.items()` in line 43 of alpaca/data/models/bars.py

RAW data of historical_data_client.get_stock_snapshot:
{'latestTrade': {'t': '2023-06-17T00:00:00.00149504Z', 'x': 'A', 'p': 4.94, 's': 5569, 'c': [' ', 'M'], 'i': 52983526405938, 'z': 'B'}, 'latestQuote': {'t': '2023-06-16T23:59:58.698732032Z', 'ax': 'P', 'ap': 4.93, 'as': 3, 'bx': 'P', 'bp': 4.91, 'bs': 9, 'c': ['R'], 'z': 'B'}, 'minuteBar': {'t': '2023-06-16T23:59:00Z', 'o': 4.9, 'h': 4.93, 'l': 4.9, 'c': 4.93, 'v': 1735, 'n': 12, 'vw': 4.915245}, 
'dailyBar': {'t': '2023-06-16T04:00:00Z', 'o': 4.26, 'h': 5.18, 'l': 4.26, 'c': 4.94, 'v': 947811, 'n': 5893, 'vw': 4.702219}, 
'prevDailyBar': None}

**Comment by haxdds** [comment]
This issue is related to https://github.com/alpacahq/alpaca-py/issues/230 and https://github.com/alpacahq/alpaca-py/issues/282


I'm closing this and opening up: https://github.com/alpacahq/alpaca-py/issues/317 to clean up the issues a bit and reduce duplication.

Please follow along there.
