### ISSUE TITLE
[Bug]: Out of range float values are not JSON compliant

### ISSUE THREAD

**Issue by sshcli** [alpacahq/alpaca-py#191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sometimes I get this error:
`raise InvalidJSONError(ve, request=self) requests.exceptions.InvalidJSONError: Out of range float values are not JSON compliant`

```
Out of range float values are not JSON compliant
Traceback (most recent call last):
  File "\Python39\lib\site-packages\requests\models.py", line 473, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
	
	
  File "\Python39\lib\json\__init__.py", line 234, in dumps
    return cls(
	
	
  File "\Python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
	
	
  File "\Python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
	
	
ValueError: Out of range float values are not JSON compliant

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\test.py", line 19505, in main
    test_functiont()
  File "\test.py", line 5921, in long_market
    lo = LimitOrderRequest(symbol=s, limit_price=p, qty=q, side=OrderSide.BUY, time_in_force=TimeInForce.GTC, order_class='oto', take_profit=dict(limit_price=lp)); API.submit_order(order_data=lo)
  
  File "\Python39\lib\site-packages\alpaca\trading\client.py", line 89, in submit_order
    response = self.post("/orders", data)
    
  File "\Python39\lib\site-packages\alpaca\common\rest.py", line 225, in post
    return self._request("POST", path, data)
  
  File "\Python39\lib\site-packages\alpaca\common\rest.py", line 126, in _request
    return self._one_request(method, url, opts, retry)
  
  File "\Python39\lib\site-packages\alpaca\common\rest.py", line 184, in _one_request
    response = self._session.request(method, url, **opts)
  
  File "\Python39\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  
  File "\Python39\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  
  File "\Python39\lib\site-packages\requests\models.py", line 321, in prepare
    self.prepare_body(data, files, json)
  
  File "\Python39\lib\site-packages\requests\models.py", line 475, in prepare_body
    raise InvalidJSONError(ve, request=self)
requests.exceptions.InvalidJSONError: Out of range float values are not JSON compliant
```

### Expected Behavior

No errors

### SDK Version I encountered this issue in

alpaca-py v.0.6.1
Python 3.9
Paper Trading

### Steps To Reproduce

```markdown
Still don't know the root cause, because is sometimes, not always
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

### Anything else?

I don't get this error with `alpaca-trade-api version: 2.3.0`
I only get this error with `alpaca-py version: 0.6.1`

**Comment by sshcli** [comment]
The error also occurs with `alpaca-trade-api version: 2.3.0`
I believe the problem is related to ETF (Non Stock) and NAN values.

**Comment by sshcli** [comment]
In case it helps with the troubleshooting., I notice the error has gone after remove the ATR part:

```
    ##### Get Minute Bars  #######
    try:
     tod = datetime.datetime.now(pytz.timezone('America/New_York'))
     d = datetime.timedelta(minutes = 10)
     a = tod - d
     PRE_BARS = StockBarsRequest(symbol_or_symbols=[SYMBOL],timeframe=TimeFrame.Minute, start=a, end=tod)
     BARS_ATR = DATA.get_stock_bars(PRE_BARS).df.sort_values(by='timestamp', ascending=True)
    except:
     print("Can't get bars")

    ##### Get ATR  #######
    try:
     period = 14
     tr1 = abs(BARS_ATR['high'] - BARS_ATR['low'])
     tr2 = abs(BARS_ATR['high'] - BARS_ATR['close'].shift())
     tr3 = abs(BARS_ATR['low'] - BARS_ATR['close'].shift())
     ranges = pd.concat([tr1, tr2, tr3], axis=1)
     tr = ranges.max(axis=1)
     atr_all = tr.rolling(period).sum()/period
     ATR = round(atr_all.iloc[-1], 5)
     HALF_ATR = round(ATR / 2, 2)        
    except:
     print("Can't get ATR")
```

**Comment by sshcli** [comment]
I can't reproduce this error anymore in `alpaca-py 0.7.2`

I'm closing this one.
