### ISSUE TITLE
[Question]: How to submit a bracket stock order?

### ISSUE THREAD

**Issue by gerardsyd** [alpacahq/alpaca-py#272]
### Question form pre-submit checklist.

- [X] I have searched the existing issues to ensure there isn't already an issue about this question.
- [X] My question has to do with the Python SDK and isn't a general question about the API. (If it is please open your issue [here](https://github.com/alpacahq/Alpaca-API))
- [X] My question isn't about how to do a specific algorithm or asking for trade advice (answers to these are outside the scope of this repo).

### Question

I am trying to put together a bracket order to trade a stock with a take profit and stop loss. 

I think I can do it using the general Order Request but upon trying I get an error. 

Here is my code:
```
tp_params = TakeProfitRequest(limit_price=price * 1.15)
sl_params = StopLossRequest(stop_price=price * 0.9)
params = OrderRequest(symbol=symbol, qty=quantity, side=OrderSide.BUY, type=OrderType.LIMIT, limit_price=price,
                      client_order_id='test1', time_in_force=TimeInForce.DAY, take_profit=tp_params, stop_loss=sl_params, order_class=OrderClass.BRACKET)
trading_client.submit_order(params)
```

And the result I receive is:
```
Traceback (most recent call last):
  File "C:\Users\gerar\Envs\cryptobot\lib\site-packages\alpaca\common\rest.py", line 197, in _one_request
    response.raise_for_status()
  File "C:\Users\gerar\Envs\cryptobot\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://paper-api.alpaca.markets/v2/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gerar\OneDrive - HG Capital\Coding\Python\crypto_bot\test.py", line 87, in <module>
    trading_client.submit_order(params)
  File "C:\Users\gerar\Envs\cryptobot\lib\site-packages\alpaca\trading\client.py", line 91, in submit_order
    response = self.post("/orders", data)
  File "C:\Users\gerar\Envs\cryptobot\lib\site-packages\alpaca\common\rest.py", line 235, in post
    return self._request("POST", path, data)
  File "C:\Users\gerar\Envs\cryptobot\lib\site-packages\alpaca\common\rest.py", line 130, in _request
    return self._one_request(method, url, opts, retry)
  File "C:\Users\gerar\Envs\cryptobot\lib\site-packages\alpaca\common\rest.py", line 206, in _one_request
    raise APIError(error, http_error)
alpaca.common.exceptions.APIError: {"code":40010001,"message":"limit orders require a limit price"}
```

Little bit confusing as I pass the limit_price into OrderRequest. The documentation is a bit unclear on whether I can pass OrderRequest and the documentation switches to the old SDK for bracket trades so little confused. 

Any help would be appreciated.

**Comment by cryb3** [comment]
I've found that giving the bracket as dictionary parameters works:

```python
  limit_order_data = LimitOrderRequest(  symbol=symbol,
                    side=OrderSide.SELL,
                    limit_price=latest_price,
                    time_in_force=TimeInForce.DAY,
                    qty=shares_traded,
                    order_class=OrderClass.BRACKET,
                    stop_loss={"stop_price": stop_loss_trigger_price,
                                   "limit_price": stop_loss_limit_price},
                    take_profit={
                            "limit_price": take_profit_limit_price})   
                
        submit_limit_order = trading_client.submit_order(
                order_data=limit_order_data
                )

```

**Comment by haxdds** [comment]
Hi cryb3, I'm glad you got it working. It should also work using the request objects. 
In the original code, can you try passing in a `limit_price` to the `StopLossRequest`?

**Comment by cryb3** [comment]
> Hi cryb3, I'm glad you got it working. It should also work using the request objects. In the original code, can you try passing in a `limit_price` to the `StopLossRequest`?

I think you mean to tag @gerardsyd
